### ISSUE TITLE
Small critique: Don't pack it in ZIP files (unless it is data)

### ISSUE THREAD

**Issue by BradKML** [Ritika2481/Personality-Prediction-Model#1]
If a person wants to review the code online they can't open the ZIp file without downloading it.

**Comment by Ritika2481** [comment]
Oh thanks for the tip! Working on it rn

**Comment by Ritika2481** [comment]
> If a person wants to review the code online they can't open the ZIp file without downloading it.
Oh thanks for the tip! Working on it right now
